# Generated by Django 3.1 on 2022-10-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='title2',
        ),
    ]
