# Generated by Django 3.1 on 2022-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_user_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GST',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
    ]
