# Generated by Django 3.1 on 2022-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20221008_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='contact',
            field=models.CharField(default='000000', max_length=15),
        ),
    ]
