# Generated by Django 3.1 on 2022-10-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listitem_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='title1',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
